enum {
PR_CLASS=1, PR_PUBLIC, PR_VOID, PR_MAIN, PR_EXTENDS, PR_RETURN, PR_IF, PR_ELSE, PR_WHILE, PR_PRINT, PR_LENGTH, PR_TRUE, PR_FALSE, PR_THIS, PR_NEW, PR_STATIC,
TK_OK, TK_OP, TK_OC, TK_CK, TK_CP, TK_CC,
TK_STRING, TK_INT, TK_BOOLEAN,
TK_PV, TK_VIRG, TK_PF,
OP_ATRIB, OP_AND, OP_OR, OP_LARGE, OP_SMALLER, OP_SUM, OP_SUB, OP_MULT, OP_NOT,
TK_ID, TK_INTEGER
};